name: Pull Request CI

on:
    pull_request:
        branches: [main]
        types: [opened, synchronize, reopened]

jobs:
    test:
        name: Lint & Build & Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "latest"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install

            - name: Run linter
              run: yarn lint

            - name: Run build
              run: yarn build

            - name: Run tests
              run: yarn test
